### ISSUE TITLE
Created wallet page typos loose -> lose

### ISSUE THREAD

**Issue by bkbooth** [ReliantNode/myiconwallet-react#13]
A couple of typos on the created wallet page. "Loose" should be "lose".

![Annotation 2019-10-23 143833](https://user-images.githubusercontent.com/634656/67355498-173f2780-f5a3-11e9-9361-d6f45ed352f1.png)

**Comment by chauxvive** [comment]
Hello, just fixed this in a PR. New to OS. Thanks! Happy #hacktoberfest!

**Comment by bkbooth** [comment]
Thanks for your help! Happy hacktoberfest to you too!
