### ISSUE TITLE
Use native API to convert Loop to ICX

### ISSUE THREAD

**Issue by Spl3en** [ReliantNode/myiconwallet-react#21]
https://github.com/ReliantNode/myiconwallet-react/blob/e7bb54af07e71c4dfaf78f60874d2a6b425b7e7a/src/utils/convertIcx.js#L10

It should be 
```javascript
IconConverter.toNumber(IconAmount.of(value, IconAmount.Unit.LOOP).convertUnit(IconAmount.Unit.ICX))
```

So you don't need the `ICX_LOOP_RATIO` constant anymore.

**Comment by bkbooth** [comment]
Ah, thanks.

I think I'd use `IconConverter.toBigNumber(...)` since I've been trying keep numbers as `BigNumber`s as much as possible.

**Comment by Spl3en** [comment]
It totally makes sense!
